//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easycase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporateJobDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CorporateJobDetail()
        {
            this.CorporatePositions = new HashSet<CorporatePosition>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ProfileId { get; set; }
        public string LMIANo { get; set; }
        public string PositionDescription { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> PositionAvailable { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual CaseStatu CaseStatu { get; set; }
        public virtual CorporateProfileInformation CorporateProfileInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporatePosition> CorporatePositions { get; set; }
    }
}
