//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easycase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentNotes = new HashSet<DocumentNote>();
        }
    
        public long ID { get; set; }
        public Nullable<long> LinkId { get; set; }
        public string LinkTable { get; set; }
        public string OriginalName { get; set; }
        public string FileName { get; set; }
        public string DocPath { get; set; }
        public string FolderName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CretedBy { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentNote> DocumentNotes { get; set; }
    }
}
