//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easycase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationDetail
    {
        public long ID { get; set; }
        public long CaseId { get; set; }
        public string EducationHistory { get; set; }
        public string ECACompleted { get; set; }
        public string CICEnglishExam { get; set; }
        public string SpouseEducation { get; set; }
        public string CICEnglishExamSpouse { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Case Case { get; set; }
    }
}
