//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easycase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public long ID { get; set; }
        public Nullable<int> Year { get; set; }
        public string HolidayOfYear { get; set; }
        public string HolidayDates { get; set; }
        public string CreatedBy { get; set; }
    }
}
