//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easycase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkCas
    {
        public long ID { get; set; }
        public string UserId { get; set; }
        public long CaseId { get; set; }
    
        public virtual Case Case { get; set; }
    }
}
