//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easycase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageHour
    {
        public long ID { get; set; }
        public string Day { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string LunchStartTime { get; set; }
        public string LunchEndTime { get; set; }
        public string CreatedBy { get; set; }
    }
}
