//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easycase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mention
    {
        public long ID { get; set; }
        public long TaskId { get; set; }
        public long ClientId { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual Task Task1 { get; set; }
    }
}
