//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easycase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherDetail
    {
        public long ID { get; set; }
        public long CaseId { get; set; }
        public Nullable<bool> TemporaryWorker { get; set; }
        public Nullable<bool> SkilledWorker { get; set; }
        public Nullable<bool> TradeCertificate { get; set; }
        public Nullable<bool> ProvinceNominee { get; set; }
        public Nullable<bool> JobOffer { get; set; }
        public Nullable<bool> IsBCEmployerOffer { get; set; }
        public Nullable<int> BCDistrict { get; set; }
        public string BCJobNOC { get; set; }
        public string YearsBCRelatedJobExperience { get; set; }
        public Nullable<bool> BCCurrentEmployer { get; set; }
        public Nullable<bool> IsPostSecondaryCredentialBC { get; set; }
        public Nullable<int> Wage { get; set; }
        public Nullable<int> CLBLevel { get; set; }
        public Nullable<bool> IsECAObtained { get; set; }
        public Nullable<bool> IsTradesCertificationTrainingAuthority { get; set; }
        public string EmployementHistory { get; set; }
        public string PaymentCycle { get; set; }
        public Nullable<int> FullTimeEmployees { get; set; }
        public Nullable<int> HourlyWage { get; set; }
        public Nullable<bool> AppliedPNPFromEmployerPast { get; set; }
        public Nullable<bool> IsEmployerWillingToSupportPNP { get; set; }
        public string PositionsApplied { get; set; }
        public string SpouseEmployementHistory { get; set; }
        public Nullable<bool> FamilyLivingCanada { get; set; }
        public Nullable<bool> Children { get; set; }
        public Nullable<int> ChildrenCount { get; set; }
        public string ChildrenAges { get; set; }
        public Nullable<int> Networth { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Case Case { get; set; }
    }
}
