//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easycase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceFee
    {
        public long ID { get; set; }
        public string ServiceName { get; set; }
        public string IsExpense { get; set; }
        public string Description { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<double> Fee { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
