//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easycase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskNote
    {
        public long ID { get; set; }
        public long TaskId { get; set; }
        public string Subject { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string NotifyUser { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CaseId { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual Case Case { get; set; }
    }
}
